"""Добавлено в поле status

Revision ID: 71e9a587689d
Revises: 313552387ab0
Create Date: 2022-10-18 21:29:46.134744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e9a587689d'
down_revision = '313552387ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'status')
    # ### end Alembic commands ###